### PR TITLE
CDN fonts

### PR DESCRIPTION
**Pull request by m4dz**
This PR:
- clean `index.html` template code and build files
- add defaults fonts and font-face definitions
- add favicons/appicons
- fix some styles misfortunes
- add externals scripts to vendors

### CODE REVIEW

**Comment by jsilvestre** [comment]
There is a bug: checkbox icon is not showed when adding a todo.

**Comment by frankrousseau** [comment]
The bug was there before the Matthias PR.

**Comment by jsilvestre** [comment]
Yes, but this PR was supposed to fix it. @Benibur called me this morning asking @m4dz to fix it (he was aware of it).

**Comment by frankrousseau** [comment]
Ok

**Comment by jsilvestre** [comment]
Found: .CNE_task_btn should have font-size at 18px, not 0

**Comment by jsilvestre** [comment]
Looks good to me.

**Comment by jsilvestre** [comment]
Good to merge.

**Comment by jsilvestre** [comment]
I know it's demo time, but if you could merge I think Ben would appreciate :D

**Pull request merged**
